<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Igloo.Fleet.Domain\Igloo.Fleet.Domain.csproj" />
    <ProjectReference Include="..\Igloo.Fleet.Persistence\Igloo.Fleet.Persistence.csproj" />
  </ItemGroup>
</Project>
