"""Partial manifest-backed fixtures. No complete artifact or native qualification."""
import copy
import json
import os
import stat
from pathlib import Path
import tempfile
from types import SimpleNamespace
import unittest
from unittest.mock import patch

import test_configuration_continuation as boundary
import session_configuration as config
from target_files import TargetFiles, mount_id


class ConfigurationCompatibilityTests(unittest.TestCase):
    def setUp(self):
        self.fixture = json.loads(Path(__file__).with_name('configuration_manifest_fixture.json').read_bytes())
        self.manifest = {'Entries': self.fixture['Entries']}
        self.plan = boundary.ConfigurationBoundaryTests().plan()
        self.parameters = {'Fstab': 'UUID=fixture / ext4 defaults 0 1\n', 'AptSources': 'fixture sources\n'}
        self.baseline = {'Exim': self.fixture['Exim'], 'UserDefaults': self.fixture['PublicFileBytes']['/etc/default/useradd']}

    def review(self, manifest=None):
        return config.compatibility(manifest or self.manifest, self.plan, self.parameters, self.baseline)

    def test_entire_plan_accepts_authenticated_shapes_and_ordered_outputs(self):
        rows = self.review()
        self.assertEqual([], [r for r in rows if r['Failures']])
        self.assertEqual(14, sum(r['Operation'] in ('Utf8File', 'SymbolicLink') for r in rows))
        by_path = {r['Path']: r for r in rows}
        self.assertEqual('File', by_path['/etc/locale.conf']['Before']['Type'])
        self.assertEqual('../locale.conf', by_path['/etc/default/locale']['Before']['Target'])
        self.assertEqual('PreserveLink', by_path['/usr/share/locale/locale.alias']['Operation'])
        self.assertIn('/boot/efi', self.fixture['Absent'])
        for path in ('/usr/lib/locale/locale-archive', '/var/lib/exim4/config.autogenerated', '/home/iglootest'):
            self.assertIsNone(by_path[path]['Before'])
            self.assertEqual('CreateByHelper', by_path[path]['Operation'])
        self.assertEqual([0, 104, 0o644], by_path['/var/lib/exim4/config.autogenerated']['AfterOwnerGroupMode'])
        self.assertLess(config.STEPS.index('Files'), config.STEPS.index('Exim'))

    def test_old_locale_file_declaration_fails_without_following_link(self):
        outputs = config.files(self.plan, self.parameters, self.baseline['Exim'], self.baseline['UserDefaults'])
        outputs['/etc/default/locale'] = outputs.pop('/etc/locale.conf')
        with patch.object(config, 'files', return_value=outputs):
            self.assertTrue(any(r['Path'] == '/etc/default/locale' and r['Failures'] for r in self.review()))

    def test_reports_all_independent_mismatches_and_stops_at_unsafe_parent(self):
        manifest = copy.deepcopy(self.manifest)
        for e in manifest['Entries']:
            if e['Path'] == '/etc/default': e.update(Type='SymbolicLink', Target='/outside')
            if e['Path'] == '/etc/locale.conf': e.update(Type='Directory')
            if e['Path'] == '/mnt': e.update(Mode=0o777)
        rows = self.review(manifest)
        self.assertTrue(next(r for r in rows if r['Path'] == '/etc/locale.conf')['Failures'])
        self.assertEqual(['UnsafeOrMissingParent:/etc/default'],
                         next(r for r in rows if r['Path'] == '/etc/default/keyboard')['Failures'])

    def test_substituted_links_and_unsupported_output_metadata_rejected(self):
        for path, fields in [('/etc/default/locale', {'Target': '/outside'}),
                             ('/usr/share/locale/locale.alias', {'Target': '/other'}),
                             ('/etc/locale.conf', {'Type': 'SymbolicLink', 'Target': '/outside'}),
                             ('/etc/fstab', {'Xattrs': {'security.unknown': '00'}})]:
            with self.subTest(path=path):
                manifest = copy.deepcopy(self.manifest)
                next(e for e in manifest['Entries'] if e['Path'] == path).update(fields)
                self.assertTrue(any(r['Failures'] for r in self.review(manifest)))

    def test_native_preflight_uses_exact_before_state_and_rejects_changed_content(self):
        states = {r['Path']: config.before_state(r['Before']) for r in self.review()
                  if r['Operation'] in ('Utf8File', 'SymbolicLink', 'PreserveLink')}
        with patch.object(config, 'TargetFiles') as factory:
            factory.return_value.__enter__.return_value.observe.side_effect = states.__getitem__
            view = SimpleNamespace(fd=10, expected=(1, 2, 3))
            config.preflight_files(view, self.manifest, self.plan, self.parameters, self.baseline)
            states['/etc/locale.conf'] = {**states['/etc/locale.conf'], 'Sha256': '0'*64}
            with self.assertRaisesRegex(ValueError, 'ConfigurationMountedPreflightRejected'):
                config.preflight_files(view, self.manifest, self.plan, self.parameters, self.baseline)

    def test_real_fd_relative_writer_preserves_locale_link_and_specific_links(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            outputs = config.files(self.plan, self.parameters, self.baseline['Exim'], self.baseline['UserDefaults'])
            selected = set(outputs) | {'/etc/default/locale'}
            original = {e['Path']: e for e in self.fixture['Entries']}
            for path in selected:
                leaf = root/path[1:]; leaf.parent.mkdir(parents=True, exist_ok=True)
                entry = original.get(path)
                if entry and entry['Type'] == 'SymbolicLink': leaf.symlink_to(entry['Target'])
                elif entry:
                    leaf.write_bytes(self.fixture['PublicFileBytes'][path].encode()); leaf.chmod(entry['Mode'])
            fd = os.open(root, os.O_RDONLY | os.O_DIRECTORY)
            try:
                with TargetFiles(fd, os.fstat(fd).st_dev, mount_id(fd), os.getuid(), os.getgid()) as target:
                    for path, (kind, value, mode) in outputs.items():
                        # Ownership is mapped to the fixture runner only. Original
                        # authenticated metadata is retained unmodified in the fixture.
                        expected = config.before_state(original.get(path))
                        if expected['Kind'] != 'Absent': expected.update(Owner=os.getuid(), Group=os.getgid())
                        self.assertEqual(expected, target.observe(path))
                        target.apply(path, kind, value, mode, expected)
                    self.assertEqual('../locale.conf', os.readlink(root/'etc/default/locale'))
                    self.assertEqual('LANG=en_US.UTF-8\n', (root/'etc/locale.conf').read_text())
                    self.assertFalse((root/'boot/efi').exists())
                    with self.assertRaisesRegex(ValueError, 'RefuseFileOverSymlink'):
                        target.apply('/etc/default/locale', 'Utf8File', 'bad', 0o644, target.observe('/etc/default/locale'))
            finally: os.close(fd)

    def test_exim_uses_authenticated_debian_exim_group_not_root_or_observed_gid(self):
        path = '/var/lib/exim4/config.autogenerated'
        baseline = {'/etc/group': 'root:x:0:\nDebian-exim:x:104:\n'}
        content = b'DC_eximconfig_configtype=local\nETC_MAILNAME=igloo-lab-config\n'
        for gid, mode, expected in ((104, 0o644, True), (0, 0o644, False), (105, 0o644, False), (104, 0o666, False)):
            actual = {path: (SimpleNamespace(st_mode=stat.S_IFREG | mode, st_uid=0, st_gid=gid,
                st_size=len(content), st_nlink=1), None, {}, 'fixture')}
            with self.subTest(gid=gid, mode=mode), patch.object(config.root, 'read_small', return_value=content):
                if expected: config.verify_exim(None, actual, self.plan, baseline)
                else:
                    with self.assertRaisesRegex(ValueError, 'ConfigurationOutputMetadata'):
                        config.verify_exim(None, actual, self.plan, baseline)
        with self.assertRaisesRegex(ValueError, 'EximGroupBindingChanged'):
            config.verify_exim(None, {}, self.plan, {'/etc/group': 'Debian-exim:x:105:\n'})

    def test_exim_rejects_wrong_type_uid_links_and_metadata(self):
        path = '/var/lib/exim4/config.autogenerated'
        for mode, uid, links, target, attrs in (
                (stat.S_IFREG | 0o644, 1, 1, None, {}),
                (stat.S_IFLNK | 0o777, 0, 1, '/other', {}),
                (stat.S_IFDIR | 0o644, 0, 1, None, {}),
                (stat.S_IFREG | 0o644, 0, 2, None, {}),
                (stat.S_IFREG | 0o644, 0, 1, None, {'security.unknown': 'x'})):
            actual = {path: (SimpleNamespace(st_mode=mode, st_uid=uid, st_gid=104,
                st_size=1, st_nlink=links), target, attrs, 'fixture')}
            with self.subTest(mode=mode, uid=uid, links=links, attrs=attrs):
                with self.assertRaisesRegex(ValueError, 'ConfigurationOutputMetadata'):
                    config.verify_exim(None, actual, self.plan, {'/etc/group': 'Debian-exim:x:104:\n'})

    def test_temporary_and_unknown_exim_paths_are_not_delta_outputs(self):
        for path in ('/var/lib/exim4/config.autogenerated.tmp', '/etc/exim4/unexpected'):
            with self.subTest(path=path), patch.object(config, 'entries', return_value={path: None}):
                with self.assertRaisesRegex(ValueError, 'UndeclaredConfigurationPath'):
                    config.verify_delta(None, self.manifest, self.plan, self.parameters, 'Exim', self.baseline, None)

    def test_helper_contract_fixture_and_canonical_dispatch_share_closed_commands(self):
        commands = config.helper_commands(self.plan)
        self.assertEqual({'Debconf', 'Exim', 'Tls', 'Locale', 'User', 'Credential', 'Sudo'}, set(commands))
        self.assertEqual(('ConfigureIdentity', '/usr/sbin/update-exim4.conf', (), 'None'), commands['Exim'])
        self.assertEqual(('ConfigureUser', '/usr/sbin/chpasswd', ('--encrypted',), 'EncryptedPassword'), commands['Credential'])
        self.assertNotIn('CREATE_MAIL_SPOOL=no', commands['User'][2])
        with self.assertRaisesRegex(ValueError, 'UnsupportedCoreProfile'):
            config.helper_commands({**self.plan, 'TransformationPolicy': 'debian-trixie-core-configuration-v2'})

    def test_mail_spool_policy_uses_exact_useradd_defaults_not_login_defs_override(self):
        original = self.baseline['UserDefaults']
        outputs = config.files(self.plan, self.parameters, self.baseline['Exim'], original)
        kind, value, mode = outputs['/etc/default/useradd']
        self.assertEqual(('Utf8File', 0o644), (kind, mode))
        self.assertEqual(original.replace('# CREATE_MAIL_SPOOL=no\n', 'CREATE_MAIL_SPOOL=no\n'), value)
        self.assertEqual(1, value.splitlines().count('CREATE_MAIL_SPOOL=no'))
        for changed in (original + '\n', original.replace('SHELL=/bin/sh', 'SHELL=/bin/bash'),
                        original.replace('# CREATE_MAIL_SPOOL=no', 'CREATE_MAIL_SPOOL=yes')):
            with self.subTest(changed=changed == original), self.assertRaisesRegex(ValueError, 'UserDefaultsBeforeStateChanged'):
                config.files(self.plan, self.parameters, self.baseline['Exim'], changed)

    def test_mail_defaults_substitution_and_old_policy_are_rejected(self):
        for fields in ({'Type': 'SymbolicLink', 'Target': '/outside'}, {'Mode': 0o666}, {'Gid': 104}):
            manifest = copy.deepcopy(self.manifest)
            next(e for e in manifest['Entries'] if e['Path'] == '/etc/default/useradd').update(fields)
            self.assertTrue(any(r['Failures'] for r in self.review(manifest)))
        for version in (3, 4):
            with self.assertRaisesRegex(ValueError, 'UnsupportedCoreProfile'):
                config.helper_commands({**self.plan, 'TransformationPolicy': f'debian-trixie-core-configuration-v{version}'})


if __name__ == '__main__': unittest.main()
