"""Versioned factory-only neutralization and readback, never target dispatch.

Every changed object is nominated by the retained raw observation. This module
does not discover a disk, authorize a destination or recursively remove a tree.
The factory harness supplies an exclusively owned *derived* root FD. Package
helpers are invoked by that harness only inside the disposable offline VM.
"""
import base64
import copy
import hashlib
import os
import re
import stat

import configured_root as artifact
from target_files import beneath

PLAN = "debian-trixie-neutralization-2026-09-28-v2"
KERNEL = "6.12.107+deb13-amd64"
RUNTIME = ("/dev", "/proc", "/sys", "/run", "/tmp", "/boot/efi")
REMOVALS = {
    "/etc/hostname": "Hostname",
    "/etc/mailname": "MailIdentity",
    "/var/lib/exim4/config.autogenerated": "MailIdentity",
    "/etc/ssl/private/ssl-cert-snakeoil.key": "TlsIdentity",
    "/etc/ssl/certs/ssl-cert-snakeoil.pem": "TlsIdentity",
    "/etc/ssl/certs/66d6b83e.0": "TlsIdentity",
    "/etc/apt/sources.list": "AptSources",
    "/etc/apt/apt.conf.d/99mmdebstrap": "AptSources",
    "/boot/initrd.img-" + KERNEL: "Initramfs",
    "/initrd.img": "Initramfs",
    "/initrd.img.old": "Initramfs",
}
LINKS = {"/var/lib/dbus/machine-id": "/etc/machine-id",
         "/etc/resolv.conf": "/run/NetworkManager/resolv.conf"}

# These are requirements of target finalization, NOT new executable stages or
# claims that the restricted target host has already qualified these tools.
REGENERATION = {
    "Hostname": ("Absent", "Write validated hostname/hosts; bind target UTS hostname", "Exact file readback and UTS match"),
    "MailIdentity": ("No mailname/generated config; neutral Exim inputs", "Write target mailname/local-delivery inputs; debconf SET; update-exim4.conf", "Fresh debconf GET; Exim -bP and generated-config identity"),
    "TlsIdentity": ("Key, certificate and hash link absent", "make-ssl-cert generate-default-snakeoil after target hostname/UTS; before dependent services", "Fresh openssl public-key/certificate match, subject/SAN, root:ssl-cert 0640 key, root:root 0644 certificate; new identity"),
    "MachineIdentity": ("Empty machine-id; D-Bus symlink", "systemd generates per-instance ID on installed boot (empty file does not imply ConditionFirstBoot)", "Fresh unique ID and D-Bus equality; first-boot evidence remains pending"),
    "Fstab": ("Empty", "Write exact root/ESP filesystem UUIDs from fresh canonical session", "Exact file hash and canonical mount relationship"),
    "Network": ("No profiles/secrets; resolver symlink", "Install approved target profiles; NetworkManager supplies resolver at boot", "Fresh profile/owner/mode/secret-free receipt and resolver link"),
    "AptSources": ("No factory sources", "Write approved final Debian deb822 sources after offline deployment", "Exact source/keyring hashes; no factory or deployment-network fallback"),
    "User": ("Only pinned system accounts; locked root", "Create intended user using protected credential FD; validate sudo membership", "Fresh passwd/shadow classification/group/sudo check; never receipt credentials"),
    "Initramfs": ("Factory image and aliases absent; installed kernel/modules retained", "update-initramfs -c -k installed version after target configuration", "Fresh image/modules/kernel correlation; factory image hash is forbidden as final evidence"),
    "Agent": ("No migration generation or payload", "Install exact restricted worker/config/unit", "Hashes, ownership, enablement; InstalledFirstBootPending"),
    "UserData": ("No migration user data", "Exact generation-bound producer; execution still Unsupported", "Independent completion receipt; no scanning/labels/firmware"),
    "Enrollment": ("No enrollment secrets", "Explicit product handoff; execution still Unsupported", "Generation-bound success/failure evidence, not worker self-assertion"),
}


def absent():
    return {"Type": "Absent"}


def file_after(before, data):
    result = copy.deepcopy(before)
    result.update(Length=len(data), Sha256=artifact.digest(data))
    return result


def plan(raw_audit, source_audit_sha256, package_set_sha256, policy_sha256, exim_bytes):
    artifact.require(raw_audit["PackageStateQualified"], "RawPackageStateNotQualified")
    artifact.require(all(artifact.hash_value(h) for h in (source_audit_sha256, package_set_sha256, policy_sha256)), "PlanBinding")
    entries = {e["Path"]: e for e in raw_audit["Filesystem"]["Entries"]}
    changes = []
    def add(path, operation, after, reason, content=None):
        before = copy.deepcopy(entries.get(path, absent()))
        changes.append({"Path": path, "Operation": operation, "Before": before, "After": after,
                        "Responsibility": reason, "ContentBase64": base64.b64encode(content).decode() if content is not None else None})
    for path, reason in REMOVALS.items():
        artifact.require(path in entries, "ReviewedSourceObjectMissing:" + path)
        add(path, "Remove", absent(), reason)
    artifact.require(entries["/etc/ssl/certs/66d6b83e.0"]["Target"] == "ssl-cert-snakeoil.pem", "SnakeoilAliasChanged")
    for path in ("/etc/fstab", "/etc/machine-id", "/var/log/fontconfig.log"):
        artifact.require(entries[path]["Type"] == "File", "NeutralFileType")
        add(path, "Write", file_after(entries[path], b""), "Fstab" if path.endswith("fstab") else "MachineIdentity" if path.endswith("machine-id") else "Runtime", b"")
    for path, target in LINKS.items():
        artifact.require(path not in entries, "NeutralLinkBeforeState")
        add(path, "Link", {"Path": path, "Type": "SymbolicLink", "Uid": 0, "Gid": 0, "Mode": 0o777,
                           "Length": 0, "Sha256": None, "Target": target, "Xattrs": {}}, "MachineIdentity" if "dbus" in path else "Network")
    path = "/etc/exim4/update-exim4.conf.conf"
    artifact.require(artifact.digest(exim_bytes) == entries[path]["Sha256"] and
                     exim_bytes.count(b"dc_other_hostnames='igloo-factory'") == 1 and
                     exim_bytes.count(b"dc_mailname_in_oh='true'") == 1, "EximInputsChanged")
    data = exim_bytes.replace(b"dc_other_hostnames='igloo-factory'", b"dc_other_hostnames=''").replace(b"dc_mailname_in_oh='true'", b"dc_mailname_in_oh='false'")
    add(path, "Write", file_after(entries[path], data), "MailIdentity", data)
    # The File database backup is generated by the public debconf operation. Its
    # exact input is the nominated current database; remove only that old copy.
    for path in sorted(entries):
        if any(path.startswith(prefix + "/") for prefix in RUNTIME):
            add(path, "Remove", absent(), "Runtime")
    result = {"SchemaVersion": 1, "PlanVersion": PLAN, "SourceBuildId": raw_audit["BuildId"],
              "Release": "trixie", "Architecture": "amd64", "SourceAuditSha256": source_audit_sha256,
              "PackageSetSha256": package_set_sha256, "PolicySha256": policy_sha256,
              "Changes": sorted(changes, key=lambda c: (-c["Path"].count("/"), c["Path"])),
              "Debconf": {"Before": [entries[p] for p in ("/var/cache/debconf/config.dat", "/var/cache/debconf/config.dat-old")],
                          "SetEmpty": ["exim4/dc_other_hostnames", "exim4/mailname"],
                          "SetFalseFlag": "exim4/dc_other_hostnames mailname",
                          "After": "Only nominated values/flag changed; old backup absent; every other stanza unchanged"},
              "Regeneration": {k: {"SourceState": v[0], "TargetOperation": v[1], "IndependentReadback": v[2],
                                    "Failure": "FailedOrOutcomeUnknown; no automatic retry; blocks target completion"}
                               for k, v in REGENERATION.items()}}
    validate_plan(result)
    return result


def validate_plan(value):
    artifact.require(value["SchemaVersion"] == 1 and value["PlanVersion"] == PLAN and
                     value["Release"] == "trixie" and value["Architecture"] == "amd64", "NeutralizationProfile")
    paths = [c["Path"] for c in value["Changes"]]
    artifact.require(len(paths) == len(set(paths)), "DuplicateNeutralizationTarget")
    for change in value["Changes"]:
        path = change["Path"]; artifact.path_parts(path)
        operation = change["Operation"]
        allowed_remove = path in REMOVALS or any(path.startswith(p + "/") for p in RUNTIME)
        artifact.require((operation == "Remove" and allowed_remove and change["After"] == absent()) or
                         (operation == "Link" and path in LINKS and change["After"]["Target"] == LINKS[path]) or
                         (operation == "Write" and path in ("/etc/fstab", "/etc/machine-id", "/var/log/fontconfig.log", "/etc/exim4/update-exim4.conf.conf")), "UnreviewedNeutralization")
        if operation == "Write":
            data = base64.b64decode(change["ContentBase64"], validate=True)
            artifact.require(file_after(change["Before"], data) == change["After"], "NeutralizationAfterMismatch")
            artifact.require(path == "/etc/exim4/update-exim4.conf.conf" or data == b"", "NeutralContentNotEmpty")


def observe_object(view, path):
    parent, leaf = view.parent(path)
    try:
        try:
            s = os.stat(leaf, dir_fd=parent, follow_symlinks=False)
        except FileNotFoundError:
            return absent()
        kind = "Directory" if stat.S_ISDIR(s.st_mode) else "File" if stat.S_ISREG(s.st_mode) else "SymbolicLink" if stat.S_ISLNK(s.st_mode) else "CharacterDevice" if stat.S_ISCHR(s.st_mode) else "RejectedSpecial"
        result = {"Path": path, "Type": kind, "Uid": s.st_uid, "Gid": s.st_gid, "Mode": stat.S_IMODE(s.st_mode),
                  "Length": s.st_size if kind == "File" else 0, "Sha256": None,
                  "Target": os.readlink(leaf, dir_fd=parent) if kind == "SymbolicLink" else None, "Xattrs": {}}
        link = f"/proc/self/fd/{parent}/" + leaf
        result["Xattrs"] = {n: base64.b64encode(os.getxattr(link, n, follow_symlinks=False)).decode() for n in sorted(os.listxattr(link, follow_symlinks=False))}
        if kind == "File":
            artifact.require(s.st_nlink == 1, "NeutralizationHardlinkRejected")
            fd = beneath(parent, leaf, os.O_RDONLY)
            try:
                with os.fdopen(os.dup(fd), "rb") as f:
                    result["Sha256"] = hashlib.file_digest(f, "sha256").hexdigest().upper()
            finally:
                os.close(fd)
        return result
    finally:
        os.close(parent)


def apply_object(view, change):
    """Caller MUST reopen durable intent before entry, and independently read back."""
    artifact.require(observe_object(view, change["Path"]) == change["Before"], "NeutralizationBeforeChanged")
    parent, leaf = view.parent(change["Path"])
    try:
        if change["Operation"] == "Remove":
            if change["Before"]["Type"] == "Directory":
                os.rmdir(leaf, dir_fd=parent)  # empty only, never recursive
            else:
                os.unlink(leaf, dir_fd=parent)
        elif change["Operation"] == "Link":
            os.symlink(change["After"]["Target"], leaf, dir_fd=parent)
            os.chown(leaf, 0, 0, dir_fd=parent, follow_symlinks=False)
        elif change["Operation"] == "Write":
            fd = beneath(parent, leaf, os.O_WRONLY | os.O_TRUNC)
            try:
                data = memoryview(base64.b64decode(change["ContentBase64"], validate=True))
                while data:
                    count = os.write(fd, data); artifact.require(count > 0, "NeutralizationShortWrite"); data = data[count:]
                os.fsync(fd)
            finally:
                os.close(fd)
        else:
            raise artifact.Rejected("UnknownNeutralizationOperation")
        os.fsync(parent)
    finally:
        os.close(parent)
    artifact.require(observe_object(view, change["Path"]) == change["After"], "NeutralizationReadbackMismatch")


def debconf_records(data):
    result = {}
    for stanza in data.decode("utf-8").strip().split("\n\n"):
        lines = stanza.splitlines(); name = next((line[6:] for line in lines if line.startswith("Name: ")), None)
        artifact.require(name is not None and name not in result, "DebconfDatabaseMalformed")
        result[name] = lines
    return result


def verify_debconf(before, after):
    first, second = debconf_records(before), debconf_records(after)
    artifact.require(first.keys() == second.keys(), "DebconfQuestionSetChanged")
    for name in first:
        expected = first[name][:]
        if name in ("exim4/dc_other_hostnames", "exim4/mailname"):
            expected = ["Value: " if line.startswith("Value:") else line for line in expected]
            if name == "exim4/dc_other_hostnames":
                expected = [line.replace("mailname", "").replace(", ,", ",").rstrip(", ") if line.startswith("Flags:") else line for line in expected]
                expected = [line for line in expected if line != "Flags:"]
        # File driver elides empty values/flags. Compare effective values, not its
        # whitespace serialization; every unrelated field must still be identical.
        normalize = lambda lines: [line for line in lines if line.strip() not in ("Value:", "Flags:")]
        artifact.require(normalize(expected) == normalize(second[name]), "UnexpectedDebconfMutation:" + name)
    return artifact.digest(after)
