<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Igloo.Fleet.Contracts\Igloo.Fleet.Contracts.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="ColorlibHQ.AdminLTE.AspNetCore" Version="0.3.1" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Igloo.Fleet.Tests" />
  </ItemGroup>
</Project>
